sudo: required
services:
  - docker

before_install:
  - docker build -t rohanluthra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rohanluthra/react-test npm run test

after_success:
  - docker build -t rohanluthra/multi-client ./client
  - docker build -t rohanluthra/multi-nginx ./nginx
  - docker build -t rohanluthra/multi-server ./server
  - docker build -t rohanluthra/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images
  - docker push rohanluthra/multi-nginx
  - docker push rohanluthra/multi-client
  - docker push rohanluthra/multi-server
  - docker push rohanluthra/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-us-east-2-428784827445
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY